<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="Speisesaal.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="dsfsdf" title="dsfsdf" href="sfdsdf" coords="1743,184,2050,174,2080,685,1993,714,1927,736,1895,770,1887,829,1760,820" shape="poly">
    <area target="" alt="" title="" href="" coords="" shape="0">
</map>